# Docker Compose configuration for production environment
# Uses pre-built production images

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bizass-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: bizass_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API Service (Production)
  backend:
    image: bizass-backend:prod
    container_name: bizass-backend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: bizass_platform
      JWT_SECRET: ${JWT_SECRET:-U+EiJRZ+PrsuUnmnocqipOjKT53J4TvL5YUXnrrrFvk=}
      FRONTEND_URL: http://localhost
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-your-telegram-bot-token-here}
    ports:
      - "3001:3001"
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service (Production with nginx)
  frontend:
    image: bizass-frontend:prod
    container_name: bizass-frontend-prod
    restart: unless-stopped
    environment:
      BACKEND_URL: http://bizass-backend-prod:3001
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
  backend_uploads:
    driver: local

networks:
  default:
    name: bizass-prod-network
